name       : safeeyes
version    : 2.1.4
release    : 11
source     :
    - https://github.com/slgobinath/SafeEyes/archive/v2.1.4.tar.gz : 2d8384360a38c6c8e57c80dffe15c6f4a1456731f8a9bea1f837080bedf9a50b
homepage   : http://slgobinath.github.io/SafeEyes/
license    : GPL-3.0-or-later
component  : desktop
summary    : Safe Eyes is a tool to reduce and prevent repetitive strain injury (RSI)
description: |
    Protect your eyes from eye strain using this simple and beautiful, yet extensible break reminder.
rundeps    :
    - libayatana-appindicator
    - python-babel
    - python-croniter
    - python-gobject
    - python-psutil
    - python-xlib
    - python3-tkinter
    - xprintidle
    - xprop
build      : |
    %python3_setup
install    : |
    %python3_install

    # Remove duplicate icons and desktop file.
    rm -rv $installdir/usr/lib/python%python3_version%/site-packages/safeeyes/platform
