name       : safeeyes
version    : 2.1.1
release    : 5
source     :
    - https://github.com/slgobinath/SafeEyes/archive/v2.1.1.tar.gz : 3f0781e738b65069341d3b4dc1bc96551ecf0156b84d1b17b18ea8453866ad23
homepage   : http://slgobinath.github.io/SafeEyes/
license    : GPL-3.0-or-later
component  : desktop
summary    : Safe Eyes is a tool to reduce and prevent repetitive strain injury (RSI)
description: |
    Protect your eyes from eye strain using this simple and beautiful, yet extensible break reminder.
rundeps    :
    - libappindicator
    - python-babel
    - python-croniter
    - python-psutil
    - python-xlib
    - xprintidle
    - xprop
build      : |
    %python3_setup
install    : |
    %python3_install

    # Move icons and desktop entry to correct locations
    install -dm00644 $installdir/usr/share/applications
    mv $installdir/usr/lib/python3.7/site-packages/safeeyes/platform/icons $installdir/usr/share/icons
    mv $installdir/usr/lib/python3.7/site-packages/safeeyes/platform/safeeyes.desktop -t $installdir/usr/share/applications
    rm -r $installdir/usr/lib/python3.7/site-packages/safeeyes/platform
