name       : safeeyes
version    : 2.0.6
release    : 2
source     :
    - https://github.com/slgobinath/SafeEyes/archive/v2.0.6.tar.gz : a2e610103e509701a3cbba1ce7bdb48eb927fb0ccffacb0341a98c37733ddd96
license    : GPL-3.0-or-later
component  : desktop
summary    : Safe Eyes is a Free and Open Source tool for Linux users to reduce and prevent repetitive strain injury (RSI)
description: |
    Protect your eyes from eye strain using this simple and beautiful, yet extensible break reminder.
rundeps    :
    - libappindicator
    - python-babel
    - python-psutil
    - python-xlib
build      : |
    %python3_setup
install    : |
    %python3_install
