name       : safeeyes
version    : 2.1.5
release    : 12
source     :
    - https://github.com/slgobinath/SafeEyes/archive/v2.1.5.tar.gz : 3683c9d9250bc40ae2b3f507b1c124b06f3d851100668579650cbeebe25b2501
homepage   : http://slgobinath.github.io/SafeEyes/
license    : GPL-3.0-or-later
component  : desktop
summary    : Safe Eyes is a tool to reduce and prevent repetitive strain injury (RSI)
description: |
    Protect your eyes from eye strain using this simple and beautiful, yet extensible break reminder.
rundeps    :
    - libayatana-appindicator
    - python-babel
    - python-croniter
    - python-gobject
    - python-psutil
    - python-xlib
    - python3-tkinter
    - xprintidle
    - xprop
build      : |
    %python3_setup
install    : |
    %python3_install

    # Remove duplicate icons and desktop file.
    rm -rv $installdir/usr/lib/python%python3_version%/site-packages/safeeyes/platform
