name       : safeeyes
version    : 2.0.9
release    : 4
source     :
    - https://github.com/slgobinath/SafeEyes/archive/v2.0.9.tar.gz : a6264f52032c8d43b0c98166cffdd32a01d2c4a0bdb1b266b887857636383a93
license    : GPL-3.0-or-later
component  : desktop
summary    : Safe Eyes is a Free and Open Source tool for Linux users to reduce and prevent repetitive strain injury (RSI)
description: |
    Protect your eyes from eye strain using this simple and beautiful, yet extensible break reminder.
rundeps    :
    - libappindicator
    - python-babel
    - python-psutil
    - python-xlib
    - xprintidle
    - xprop
build      : |
    %python3_setup
install    : |
    %python3_install
